### PR TITLE
M

### PR DESCRIPTION
**Pull request by NovasGreat**
DRTYH

### CODE REVIEW

**Comment by ellieeet123** [comment]
hello so for some reason this repo isn't letting me add an issue but i just wanted to say hi, you are basically the first person that seems to actually care about this project lol. So yeah uh idk. just saying hi :)

**Comment by NovasGreat** [comment]
Don't even know why I made a request lol, and i was surprised when I saw your comment. I thought you were going to tell me to remove it or something

**Comment by ellieeet123** [comment]
oh haha not at all. as long as you give credit (which you did) feel free to do whatever you want :)

**Comment by NovasGreat** [comment]
ok bb thx ;)

**Comment by NovasGreat** [comment]
ly ;)

**Comment by NovasGreat** [comment]
@ellieeet123

**Pull request closed without merging**
